/**
 * Generator for the on-disk PreToolUse hook script (`~/.claude/hooks/sipcode-proxy.mjs`).
 *
 * Design note (deviation from plan v2 Task 14, surfaced deliberately):
 * The plan called for inlining all rewriter logic into the script string. We
 * instead emit a tiny self-contained `.mjs` that dynamically imports the
 * compiled, unit-tested `runRewriter` by absolute `file://` URL resolved at
 * install time. Rationale:
 *   1. No duplication of tested logic into an untested template string.
 *   2. Embedding regex inside a JS template literal corrupts `\s`/`${`.
 *   3. The hook regenerates on every `--install`, so the embedded path stays
 *      current; a removed package degrades to a no-op (`exit(0)`), never an error.
 * The locked architecture — PreToolUse + `updatedInput` — is unchanged.
 */

/** Marker used to detect/upgrade/uninstall a Sipcode-generated hook safely. */
export const SIPCODE_PROXY_HOOK_SIGNATURE = "SIPCODE_PROXY_HOOK_SIGNATURE/v3";

/**
 * @param runRewriterUrl    absolute `file://` URL to the compiled `runRewriter.js`.
 * @param hookReadDedupUrl  absolute `file://` URL to the compiled `hookReadDedup.js`.
 *                          Added in v3 (v1.6.6). Routes Read tool calls through
 *                          the re-read dedup orchestrator before falling back
 *                          to the rewriter registry.
 */
export function generateProxyHookScript(
  runRewriterUrl: string,
  hookReadDedupUrl: string,
): string {
  return `#!/usr/bin/env node
// ${SIPCODE_PROXY_HOOK_SIGNATURE}
// Auto-generated by \`sipcode proxy --install\`. Do not edit by hand.
//
// Reads a PreToolUse event on stdin. Two paths:
//   1) tool_name === "Read" → ask hookReadDedup whether the file is unchanged
//      since an earlier turn in this session; if so, emit a deny+reason
//      output so Claude knows the content is already in its context.
//   2) anything else → ask runRewriter whether the input should be rewritten
//      to produce naturally-compact output; if so, emit updatedInput.
// Never throws — any failure degrades to a no-op so Claude Code is never disrupted.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

let runRewriter;
let hookReadDedup;
try {
  ({ runRewriter } = await import(${JSON.stringify(runRewriterUrl)}));
} catch {
  process.exit(0);
}
try {
  ({ hookReadDedup } = await import(${JSON.stringify(hookReadDedupUrl)}));
} catch {
  hookReadDedup = null;
}

let raw = "";
try {
  raw = readFileSync(0, "utf-8");
} catch {
  process.exit(0);
}

let input;
try {
  input = JSON.parse(raw);
} catch {
  process.exit(0);
}

let result = null;

if (input && input.tool_name === "Read" && hookReadDedup) {
  try {
    result = await hookReadDedup(input, homedir());
  } catch {
    result = null;
  }
}

if (!result || !result.hookOutput) {
  try {
    result = runRewriter(input);
  } catch {
    process.exit(0);
  }
}

if (result && result.hookOutput) {
  // Best-effort per-PID stats write. Failure here must not affect the rewrite.
  try {
    const dir = join(homedir(), ".sipcode", "proxy-stats");
    mkdirSync(dir, { recursive: true });
    const file = "proxy-stats-" + process.pid + "-" + Date.now() + ".jsonl";
    writeFileSync(join(dir, file), JSON.stringify(result.statsEntry) + "\\n", "utf-8");
  } catch {}
  try {
    process.stdout.write(JSON.stringify(result.hookOutput));
  } catch {}
}

process.exit(0);
`;
}
