/**
 * Generator for the on-disk PreToolUse hook script (`~/.claude/hooks/sipcode-proxy.mjs`).
 *
 * Design note (deviation from plan v2 Task 14, surfaced deliberately):
 * The plan called for inlining all rewriter logic into the script string. We
 * instead emit a tiny self-contained `.mjs` that dynamically imports the
 * compiled, unit-tested `runRewriter` by absolute `file://` URL resolved at
 * install time. Rationale:
 *   1. No duplication of tested logic into an untested template string.
 *   2. Embedding regex inside a JS template literal corrupts `\s`/`${`.
 *   3. The hook regenerates on every `--install`, so the embedded path stays
 *      current; a removed package degrades to a no-op (`exit(0)`), never an error.
 * The locked architecture — PreToolUse + `updatedInput` — is unchanged.
 */

/** Marker used to detect/upgrade/uninstall a Sipcode-generated hook safely. */
export const SIPCODE_PROXY_HOOK_SIGNATURE = "SIPCODE_PROXY_HOOK_SIGNATURE/v2";

/**
 * @param runRewriterUrl absolute `file://` URL to the compiled `runRewriter.js`.
 */
export function generateProxyHookScript(runRewriterUrl: string): string {
  return `#!/usr/bin/env node
// ${SIPCODE_PROXY_HOOK_SIGNATURE}
// Auto-generated by \`sipcode proxy --install\`. Do not edit by hand.
//
// Reads a PreToolUse event on stdin, asks the Sipcode rewriter whether the
// tool input should be rewritten to produce naturally-compact output, and (if
// so) emits hookSpecificOutput.updatedInput on stdout. Never throws — any
// failure degrades to a no-op so Claude Code is never disrupted.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

let runRewriter;
try {
  ({ runRewriter } = await import(${JSON.stringify(runRewriterUrl)}));
} catch {
  process.exit(0);
}

let raw = "";
try {
  raw = readFileSync(0, "utf-8");
} catch {
  process.exit(0);
}

let input;
try {
  input = JSON.parse(raw);
} catch {
  process.exit(0);
}

let result = null;
try {
  result = runRewriter(input);
} catch {
  process.exit(0);
}

if (result && result.hookOutput) {
  // Best-effort per-PID stats write. Failure here must not affect the rewrite.
  try {
    const dir = join(homedir(), ".sipcode", "proxy-stats");
    mkdirSync(dir, { recursive: true });
    const file = "proxy-stats-" + process.pid + "-" + Date.now() + ".jsonl";
    writeFileSync(join(dir, file), JSON.stringify(result.statsEntry) + "\\n", "utf-8");
  } catch {}
  try {
    process.stdout.write(JSON.stringify(result.hookOutput));
  } catch {}
}

process.exit(0);
`;
}
