import { describe, expect, it } from "vitest";
import { InMemoryFs } from "../../../src/lib/fs.js";
import {
  loadRepoContext,
  parseFilesScannedFromManifest,
  parseFrameworkFromManifest,
  manifestTokensFor,
} from "../../../src/modules/estimate/repoContext.js";

const SAMPLE_MANIFEST = [
  "# Project manifest — demo",
  "",
  "Generated by sipcode.",
  "",
  "- generated-at: 2026-05-18T12:00:00Z",
  "- git-head: abc1234",
  "- files-scanned: 87",
  "",
  "## Framework",
  "",
  "- framework: next-app",
  "- build-tool: vite",
  "- languages: typescript",
  "",
].join("\n");

describe("parseFilesScannedFromManifest", () => {
  it("extracts the files-scanned count", () => {
    expect(parseFilesScannedFromManifest(SAMPLE_MANIFEST)).toBe(87);
  });

  it("returns 0 when the header line is missing", () => {
    expect(parseFilesScannedFromManifest("nothing here")).toBe(0);
  });

  it("handles varied whitespace", () => {
    expect(parseFilesScannedFromManifest("- files-scanned:   42")).toBe(42);
  });
});

describe("parseFrameworkFromManifest", () => {
  it("extracts framework label", () => {
    expect(parseFrameworkFromManifest(SAMPLE_MANIFEST)).toBe("next-app");
  });

  it("returns 'unknown' when missing", () => {
    expect(parseFrameworkFromManifest("foo bar")).toBe("unknown");
  });
});

describe("manifestTokensFor", () => {
  it("returns positive integer for non-empty content", () => {
    const n = manifestTokensFor(SAMPLE_MANIFEST);
    expect(Number.isInteger(n)).toBe(true);
    expect(n).toBeGreaterThan(0);
  });
});

describe("loadRepoContext", () => {
  it("uses manifest when present", async () => {
    const fs = new InMemoryFs();
    fs.writeFile("/proj/.sipcode/manifest.md", SAMPLE_MANIFEST);
    const r = await loadRepoContext(fs, "/proj");
    expect(r.manifestPresent).toBe(true);
    expect(r.fileCount).toBe(87);
    expect(r.framework).toBe("next-app");
    expect(r.manifestTokens).toBeGreaterThan(0);
    expect(r.fallbackNote).toBe("");
  });

  it("falls back to quick scan when manifest absent", async () => {
    const fs = new InMemoryFs();
    fs.writeFile("/proj/src/index.ts", "export const x = 1;");
    fs.writeFile("/proj/src/util.ts", "export const y = 2;");
    fs.writeFile("/proj/package.json", "{}");
    const r = await loadRepoContext(fs, "/proj");
    expect(r.manifestPresent).toBe(false);
    expect(r.framework).toBe("unknown");
    expect(r.fileCount).toBeGreaterThan(0);
    expect(r.fallbackNote).toMatch(/no manifest/);
  });

  it("returns zeroed context when manifestOnly + missing", async () => {
    const fs = new InMemoryFs();
    fs.writeFile("/proj/src/a.ts", "x");
    const r = await loadRepoContext(fs, "/proj", { manifestOnly: true });
    expect(r.manifestPresent).toBe(false);
    expect(r.fileCount).toBe(0);
    expect(r.fallbackNote).toMatch(/no manifest/);
  });

  it("handles malformed manifest by falling back", async () => {
    const fs = new InMemoryFs();
    fs.writeFile("/proj/.sipcode/manifest.md", "completely garbage");
    fs.writeFile("/proj/src/x.ts", "x");
    const r = await loadRepoContext(fs, "/proj");
    // Even on garbage content, file existed → marked manifestPresent=true
    // with whatever could be parsed (0 / unknown).
    expect(r.manifestPresent).toBe(true);
    expect(r.fileCount).toBe(0);
    expect(r.framework).toBe("unknown");
  });
});
