/**
 * render — compose the manifest.md content from inputs.
 *
 * Pure. Deterministic ordering everywhere — re-running with identical
 * inputs produces byte-identical output.
 */
import { approxTokenCount } from "../../lib/tokenizer.js";
import type {
  DetectedPatterns,
  FrameworkFingerprint,
  HotFile,
  ImportGraph,
  ManifestInputs,
  ParsedFile,
  RenderedManifest,
  ScannedFile,
} from "./types.js";

/** Sections of the manifest, in the order they appear. */
export type ManifestSection =
  | "header"
  | "framework"
  | "patterns"
  | "fileTree"
  | "hotFiles"
  | "importGraph";

export interface RenderOptions {
  /**
   * Sections to include, in display order. When --tighten drops sections,
   * the caller passes a filtered list here. The render is otherwise stable.
   */
  readonly sections?: ReadonlyArray<ManifestSection>;
  /**
   * Compact the file tree: drop per-file purpose lines, keep just paths.
   * Roughly halves the file tree section size.
   */
  readonly compactFileTree?: boolean;
  /**
   * Tightening step: when true, render the file tree as directories
   * only (no individual files listed). Catastrophically smaller than
   * compact mode on medium+ repos. Used by --tighten as a fallback
   * before dropping the section entirely. Introduced v1.1.1.
   */
  readonly directoryTreeOnly?: boolean;
}

const DEFAULT_SECTIONS: ReadonlyArray<ManifestSection> = [
  "header",
  "framework",
  "patterns",
  "fileTree",
  "hotFiles",
  "importGraph",
];

export function renderManifest(
  inputs: ManifestInputs,
  opts: RenderOptions = {},
): RenderedManifest {
  const sections = opts.sections ?? DEFAULT_SECTIONS;
  const parts: string[] = [];

  for (const s of sections) {
    switch (s) {
      case "header":
        parts.push(renderHeader(inputs));
        break;
      case "framework":
        parts.push(renderFramework(inputs.framework));
        break;
      case "patterns":
        parts.push(renderPatterns(inputs.patterns));
        break;
      case "fileTree":
        parts.push(
          renderFileTree(inputs.files, inputs.parsed, opts.compactFileTree ?? false, opts.directoryTreeOnly ?? false),
        );
        break;
      case "hotFiles":
        if (inputs.hotFiles.length > 0) {
          parts.push(renderHotFiles(inputs.hotFiles));
        }
        break;
      case "importGraph":
        parts.push(renderImportGraph(inputs.importGraph));
        break;
    }
  }

  const content = parts.join("\n") + "\n";
  return { content, tokenCount: approxTokenCount(content) };
}

function renderHeader(inputs: ManifestInputs): string {
  const head = inputs.headShort ?? "(no-git)";
  return [
    `# Project manifest — ${inputs.projectName}`,
    "",
    `Generated by sipcode. Single source of truth for codebase shape.`,
    `Don't grep before reading this.`,
    "",
    `- generated-at: ${inputs.generatedAt}`,
    `- git-head: ${head}`,
    `- files-scanned: ${inputs.files.length}`,
    "",
  ].join("\n");
}

function renderFramework(f: FrameworkFingerprint): string {
  return [
    "## Framework",
    "",
    `- framework: ${f.framework}`,
    `- build-tool: ${f.buildTool}`,
    `- languages: ${f.languages.length > 0 ? f.languages.join(", ") : "unknown"}`,
    "",
  ].join("\n");
}

function renderPatterns(p: DetectedPatterns): string {
  return [
    "## Detected patterns",
    "",
    `- import-style: ${p.importStyle}`,
    `- naming: ${p.naming}`,
    `- test-framework: ${p.testFramework}`,
    `- package-manager: ${p.packageManager}`,
    `- monorepo-layout: ${p.monorepo}`,
    "",
  ].join("\n");
}

/**
 * Files we surface in the tree even though they aren't a supported source
 * language — high-signal config/docs that the agent actually needs to know
 * exist. Anything else with language "other" is dropped from the tree to
 * keep the manifest tight.
 */
const KEEP_OTHER_BASENAMES = new Set([
  "README.md",
  "package.json",
  "tsconfig.json",
  "vitest.config.ts",
  "vite.config.ts",
  "next.config.js",
  "next.config.ts",
  "astro.config.mjs",
  "astro.config.ts",
  "pyproject.toml",
  "setup.py",
  "go.mod",
  "Cargo.toml",
  "Dockerfile",
  ".sipcodeignore",
  ".gitignore",
]);

function renderFileTree(
  scanned: ReadonlyArray<ScannedFile>,
  parsed: ReadonlyArray<ParsedFile>,
  compact: boolean,
  directoryOnly: boolean,
): string {
  const purposes = new Map<string, string>();
  for (const p of parsed) purposes.set(p.path, p.purpose);

  const filtered = scanned.filter((f) => {
    if (f.language !== "other") return true;
    const base = f.path.split("/").pop() ?? "";
    return KEEP_OTHER_BASENAMES.has(base);
  });

  const lines: string[] = ["## File tree", ""];
  const tree = groupByDir(filtered);
  // directoryOnly: render only directory headings + counts, no files.
  if (directoryOnly) {
    const dirsOnly = [...tree.keys()].sort();
    for (const dir of dirsOnly) {
      if (dir === "") {
        const rootCount = (tree.get("") ?? []).length;
        if (rootCount > 0) lines.push("- `./` (" + rootCount + " file(s) at repo root)");
      } else {
        const dirCount = (tree.get(dir) ?? []).length;
        lines.push("- `" + dir + "/` (" + dirCount + " file(s))");
      }
    }
    lines.push("");
    return lines.join("\n");
  }
  // Render in alphabetical order, dir-first.
  const dirs = [...tree.keys()].sort();
  for (const dir of dirs) {
    if (dir === "") {
      // root files first under no heading
    } else {
      lines.push(`### ${dir}/`);
      lines.push("");
    }
    const files = (tree.get(dir) ?? []).slice().sort((a, b) =>
      a.path.localeCompare(b.path),
    );
    for (const f of files) {
      if (compact) {
        lines.push(`- \`${f.path}\``);
        continue;
      }
      const purpose = purposes.get(f.path);
      const label = purpose ? ` — ${purpose}` : "";
      lines.push(`- \`${f.path}\`${label}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function groupByDir(
  scanned: ReadonlyArray<ScannedFile>,
): Map<string, ScannedFile[]> {
  const out = new Map<string, ScannedFile[]>();
  for (const s of scanned) {
    const slash = s.path.lastIndexOf("/");
    const dir = slash < 0 ? "" : s.path.slice(0, slash);
    const bucket = out.get(dir) ?? [];
    bucket.push(s);
    out.set(dir, bucket);
  }
  return out;
}

function renderHotFiles(hot: ReadonlyArray<HotFile>): string {
  const lines: string[] = ["## Hot files (last 90 days)", ""];
  for (const h of hot) {
    lines.push(`- \`${h.path}\` — ${h.changes} change${h.changes === 1 ? "" : "s"}`);
  }
  lines.push("");
  return lines.join("\n");
}

function renderImportGraph(g: ImportGraph): string {
  const lines: string[] = ["## Import graph (top intra-project imports)", ""];
  const keys = [...g.edges.keys()].sort();
  for (const k of keys) {
    const imports = g.edges.get(k);
    if (!imports || imports.length === 0) continue;
    lines.push(`- \`${k}\` → ${imports.map((i) => `\`${i}\``).join(", ")}`);
  }
  lines.push("");
  return lines.join("\n");
}
